// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ArtistSortController from "./artist_sort_controller.js"
application.register("artist-sort", ArtistSortController)

import FuzzySearchController from "./fuzzy_search_controller.js"
application.register("fuzzy-search", FuzzySearchController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)
